### PR TITLE
Cleanup #3

### PR DESCRIPTION
**Pull request by ghadishayban**
Remove some unnecessary statics around the apiBase handling.
Unify put()/post() approaches.

Remove a non-useful test around provider counts.

### CODE REVIEW

**Comment by dixonwh** [comment]
To round things out, I would recommend adding some javadoc documentation to each of the classes and methods.

**Comment by riney** [comment]
I'll take that on. 

--riney

**Comment by riney** [comment]
Good stuff @ghadishayban - I'll do a separate branch/PR for Javadocs.

**Comment by kkdok** [comment]
Here are javadocs for identity...or i can push them:

`
/*
 * createIdentity
 * Creates an identity resource.
 * @param params The map containing the identity request data.
 * @return The new identity resource.
 */

/*
 * updateIdentity
 * Updates an existing identity resource.
 * @param uuid The identity resource's uuid.
 * @param params The updated identity resource.
 * @return The new identity resource.
 */

/*
 * identity
 * Queries for an existing identity resource by uuid (exact match)
 * @param uuid The identity resource's uuid.
 * @return zero or one results
 */

/*
 * identity
 * Queries for an existing identity resource by query parameters such as first_name, last_name, email, etc.
 * @param params The query parameters using resource fields such as first_name, last_name, email, etc.
 * @return zero or more results
 */

/*
 * identity
 * Queries for an existing identity resource by uuid or for multiple resources using parameters.
 * @param uuid The identity resource uuid. Used to execute an exact match query by uuid.
 * @param params Additional query parameters using resource fields such as first_name, last_name, email, etc.
 * @return zero or one result if uuid is used. Zero or more results if kwargs are used.
 */
`

**Comment by kkdok** [comment]
I have the javadocs for identity endpoints. I can add them and push or slack them to you JR

**Pull request merged**
